name: meread
description: MeRead

publish_to: "none"

version: 0.6.1+23

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite:
  path:
  shared_preferences:
  provider:
  share_plus:
  opml:
  url_launcher:
  path_provider:
  html:
  html_main_element:
  dio:
  dynamic_color:
  intl: any
  file_picker:
  xml:
  fluttertoast:
  isar:
  isar_flutter_libs:
  flutter_inappwebview:
  flutter_widget_from_html:
  window_manager:
  flutter_displaymode:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  isar_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/meread.png
    - assets/avatar.png
  generate: true

  fonts:
    - family: 默认字体
      fonts:
        - asset: assets/sarasa-ui-sc.ttf
